App/urls.py
from django.conf.urls import url
from App.views import views, user, posts, owncenter, comment

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^index/$', views.index),
    url(r'^register/$', user.register, name='register'),
    url(r'^userActivate/(\w+)/$', user.userActivate, name='userActivate'),
    url(r'^login/$', user.Login, name='login'),
    url(r'^logout/$', user.Logout, name='logout'),
    url(r'^verifycode/$', user.verifycode, name='verifycode'),
    url(r'^send_posts/$', posts.send_posts, name='send_posts'),
    url(r'^update_posts/$', posts.update_posts, name='update_posts'),
    url(r'^posts_detail/$', posts.posts_detail, name='posts_detail'),
    url(r'^search_posts/$', posts.search_posts, name='search_posts'),
    url(r'^upload/$', user.upload, name='upload'),
    url(r'^posts_manager/$', posts.posts_manager, name='posts_manager'),
    url(r'^delete_posts/$', posts.delete_posts, name='delete_posts'),
    url(r'^update_username/$', owncenter.update_username, name='update_username'),
    url(r'^update_password/$', owncenter.update_password, name='update_password'),
    url(r'^do_favourite/$', posts.do_favourite, name='do_favourite'),
    url(r'^delete_favourite/$', posts.delete_favourite, name='delete_favourite'),
    url(r'^my_favourite/$', owncenter.my_favourite, name='my_favourite'),
    url(r'^send_comment/$', comment.send_comment, name='send_comment'),

]

d_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('App.urls', namespace='App'))
]

templates/home/index.html
{% extends 'common/base.html' %}
{% load static from staticfiles %}

{% block title %}
    首页
{% endblock %}
{% block pagecontent %}
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
          </ol>

          <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox" style="height: 400px;">
              <div class="item active">
                    <img src="{% static 'bananer/1.jpg' %}" alt="...">
                    <div class="carousel-caption">
                    </div>
              </div>
              <div class="item">
                    <img src="{% static 'bananer/2.jpg' %}" alt="...">
                    <div class="carousel-caption">
                    </div>
              </div>
              <div class="item">
                    <img src="{% static 'bananer/3.jpg' %}" alt="...">
                    <div class="carousel-caption">
                    </div>
              </div>
            </div>
          <!-- Controls -->
          <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
    </div>
    {% for posts in page.object_list %}
        <div class="media">
            <a href="{% url 'App:posts_detail' %}?id={{ posts.id }}" style="color: black;text-decoration: none;">
                <div class="media-left media-middle">
                    <img class="media-object" src="{% static posts.user.icon %}" alt="..."
                         width="100">
                </div>
                <div class="media-body">
                    <h4 class="media-heading">{{ posts.title }} <span
                            style="float: right;color: #ccc;font-size:14px;">{{ posts.upload_time|date:'Y-m-d H:i:s' }}</span>
                    </h4>
                    {{ posts.article }}
                </div>
            </a>
            <HR style="border:1px dashed #987cb9" width="100%" color=#987cb9 SIZE=1>
        </div>
    {% endfor %}

    <nav aria-label="Page navigation">
    <ul class="pagination">
        <li {% if not page.has_previous %}class="disabled"{% endif %}>
        <a {% if page.has_previous %}href="{% url 'App:index' %}?page={{ page.previous_page_number }}"{% endif %} aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
        </a>
        </li>
        {% for i in page.paginator.page_range %}
            <li {% if page.number == i %}class="active"{% endif %}><a href="{% url 'App:index' %}?page={{ i }}">{{ i }}</a></li>
        {% endfor %}
        <li {% if not page.has_next %}class="disabled"{% endif %}>
            <a {% if page.has_next %}href="{% url 'App:index' %}?page={{ page.next_page_number }}"{% endif %} aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
    </nav>
{% endblock %}

templates/home/login.html
{% extends 'common/base.html' %}

{% block title %}
登录
{% endblock %}

{% block pagecontent %}
    <h2>登录</h2>
    <br>
    <br>
    <div class="row">
        <div class="col-md-4">
            <form method="post" action="{% url 'App:login' %}">
                {% csrf_token %}
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">用户名</span>
                <input type="text" class="form-control" placeholder="请输入用户名" aria-describedby="basic-addon1" name="username">
            </div>
            <br>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">密码</span>
                <input type="password" class="form-control" placeholder="请输入密码" aria-describedby="basic-addon1" name="password">
            </div>
            <br>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">验证码</span>
                <input type="text" class="form-control" placeholder="请输入验证码" aria-describedby="basic-addon1" name="randcode">

            </div>
                <img src="{% url 'App:verifycode' %}" alt="" onclick="this.src='/verifycode/?id='+Math.random()" style="cursor: pointer;">
                <span><a href="#">已有账户，未激活？</a></span>
                <br>
                <br>
{#            <span> <a href="{{ url_for('huser.again_activate',_external=True) }}">已有账户 未激活？</a></span>#}
            <div class="btn-group" role="group" aria-label="...">
                <button type="submit" class="btn btn-default">登录</button>
    {#            <button type="button" class="btn btn-default">Right</button>#}
            </div>
            </form>
        </div>
        <div class="col-md-8">.col-md-8</div>
    </div>
{% endblock %}

templates/home/my_favourite.html
{% extends 'common/base.html' %}
{% load static from staticfiles %}
{% block title %}
博客管理
{% endblock %}
{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/style.css' %}" />
{% endblock %}
{% block pagecontent %}
<form class="form-inline definewidth m20" action="{% url 'App:my_favourite' %}" method="post">
    {% csrf_token %}
    标题名称：
    <input type="text" name="titleword" id="username" class="abc input-default" placeholder="按标题查询" value="{{ word }}">&nbsp;&nbsp;
    <button type="submit" class="btn btn-primary">查询</button>&nbsp;&nbsp;
{#    <button type="button" class="btn btn-success" id="addnew">新增用户</button>#}
</form>
<table class="table table-bordered table-hover definewidth m10">
    <thead>
    <tr>
        <th>标题</th>
        <th>作者</th>
        <th>浏览次数</th>
        <th>发表时间</th>
        <th>上次修改时间</th>
        <th>操作</th>
    </tr>
    </thead>
    {% for row in data %}
	     <tr>
            <td>{{ row.title }}</td>
            <td>{{ row.user.username }}</td>
            <td>{{ row.visit }}</td>
            <td>{{ row.upload_time|date:'Y-m-d H:i:s' }}</td>
            <td>{{ row.update_time|date:'Y-m-d H:i:s' }}</td>
            <td>
                <a href="{% url 'App:delete_favourite' %}?id={{ row.id }}">取消收藏</a> |
                <a href="{% url 'App:posts_detail' %}?id={{ row.id }}" target="_blank">查看</a>
            </td>
        </tr>
    {% endfor %}

</table>
{% endblock %}

templates/home/posts_detail.html
{% extends 'common/base.html' %}
{% load static from staticfiles %}
{% block title %}
{{ posts.title }}
{% endblock %}

{% block pagecontent %}
    <h2 style="text-align: center">{{ posts.title }}</h2>
    <div class="page-header"><h4><strong>{{ posts.user.username }}</strong></h4>
        <p onclick="dofavorite({{ posts.id }})" style="cursor: pointer; float: right" id="collect">{% if request.user in cusers %}已收藏{% else %}收藏{% endif %}</p>
        <h5>发表于:{{ posts.upload_time|date:'Y-m-d H:i:s' }}</h5>
    </div>
{#    {{ moment(posts.timestamp).format('Y-M-D H点m分') }}<br>#}
    <textarea readonly="readonly" name="article" id="female" class="form-control" style="height: 500px" required>{{ posts.article }}</textarea>
    <div class="page-header"></div>
    <p style="float: right">浏览次数：{{ posts.visit }}</p>
    <br>
    <div>
        <form method="post" action="{% url 'App:send_comment' %}?pid={{ posts.id }}">
            {% csrf_token %}
            <h4>发表评论：</h4>
            <input type="text" placeholder="评论必须在120字以内" name="content" id="male" class="form-control" required />
            <br/>
            <button type="submit" class="btn btn-warning">评论</button>
        </form>
    </div>
    <div>
        <HR style="border:1px dashed #987cb9" width="100%" color=#987cb9 SIZE=1>
        {% for comment in comments %}
        <div class="media">
            <a href="" style="color: black;text-decoration: none;">
                <div class="media-left media-middle">
                    <img class="media-object" src="{% static comment.from_user.icon %}" alt="..."
                         width="100">
                </div>
                <div class="media-body">
                    <h4 class="media-heading"><strong>{{ comment.from_user.username }} </strong><span
                            style="color: #444444;font-size:14px;">发表于：{{ comment.create_time|date:'Y-m-d H:i:s' }}</span>
                    </h4>
                    {{ comment.content }}
                </div>
            </a>
        </div>
        {% endfor %}

    </div>
{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script>
        function dofavorite(pid) {
            node = $('p#collect');
            html = node.html();
            $.get({% url 'App:do_favourite' %},{'pid':pid},function (data,status) {
                if(data.res == 200){

                    if(html == '收藏'){
                        node.html('已收藏');
                    }else{
{#                        console.log('走了');#}
                       node.html('收藏');
                    }
                }
            });
        }
    </script>
{% endblock %}

templates/home/posts_manager.html
{% extends 'common/base.html' %}
{% load static from staticfiles %}
{% block title %}
博客管理
{% endblock %}
{% block styles %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'home/css/style.css' %}" />
{% endblock %}
{% block pagecontent %}
<form class="form-inline definewidth m20" action="{% url 'App:posts_manager' %}" method="post">
    {% csrf_token %}
    标题名称：
    <input type="text" name="titleword" id="username" class="abc input-default" placeholder="按标题查询" value="{{ word }}">&nbsp;&nbsp;
    <button type="submit" class="btn btn-primary">查询</button>&nbsp;&nbsp;
{#    <button type="button" class="btn btn-success" id="addnew">新增用户</button>#}
</form>
<table class="table table-bordered table-hover definewidth m10">
    <thead>
    <tr>
        <th>标题</th>
        <th>浏览次数</th>
        <th>发表时间</th>
        <th>上次修改时间</th>
        <th>操作</th>
    </tr>
    </thead>
    {% for row in data %}
	     <tr>
            <td>{{ row.title }}</td>
            <td>{{ row.visit }}</td>
            <td>{{ row.upload_time|date:'Y-m-d H:i:s' }}</td>
            <td>{{ row.update_time|date:'Y-m-d H:i:s' }}</td>
            <td>
                <a href="{% url 'App:update_posts' %}?id={{ row.id }}" target="_blank">编辑</a> |
                <a href="{% url 'App:delete_posts' %}?id={{ row.id }}">删除</a> |
                <a href="{% url 'App:posts_detail' %}?id={{ row.id }}" target="_blank">查看</a>
            </td>
        </tr>
    {% endfor %}

</table>
{% endblock %}

templates/home/register.html
{% extends 'common/base.html' %}

{% block title %}
    注册
{% endblock %}
{% block pagecontent %}
    <h2>注册</h2>
    <br>
    <br>
    <div class="row">
        <div class="col-md-4">
            <form method="post" action="{% url 'App:register' %}">
                {% csrf_token %}
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">用户名</span>
                <input type="text" class="form-control" placeholder="请输入用户名" aria-describedby="basic-addon1" name="username" required>
            </div>
            <br>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">密码</span>
                <input type="password" class="form-control" placeholder="请输入密码" aria-describedby="basic-addon1" name="password" required>
            </div>
            <br>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">确认密码</span>
                <input type="password" class="form-control" placeholder="再次输入密码" aria-describedby="basic-addon1" name="confirm" required>
            </div>
            <br>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">邮箱</span>
                <input type="text" class="form-control" placeholder="用于激活，务必有效" aria-describedby="basic-addon1" name="email" required>
            </div>
            <br>
{#            <span> <a href="{{ url_for('huser.again_activate',_external=True) }}">已有账户 未激活？</a></span>#}
            <div class="btn-group" role="group" aria-label="...">
                <button type="submit" class="btn btn-default">注册</button>
    {#            <button type="button" class="btn btn-default">Right</button>#}
            </div>
            </form>
        </div>
        <div class="col-md-8">.col-md-8</div>
    </div>
{% endblock %}

templates/home/search_posts.html
{% extends 'common/base.html' %}
{% load static from staticfiles %}

{% block title %}
搜索结果
{% endblock %}

{% block pagecontent %}
<div class="page-header"><h2>搜索结果为...</h2></div>
    {% if page.paginator.count == 0 %}
        <h4>没有搜索到与<strong>"{{ words }}"</strong>相关博客......</h4>
        {% else %}
        {% for post in page.object_list %}
        <div class="media">
                <a href="{% url 'App:posts_detail' %}?/id={{ post.id }}" style="color: black;text-decoration: none;">
                    <div class="media-left media-middle">
                        <img class="media-object" src="{% static post.user.icon %}" alt="..."
                         width="100">
                    </div>
                    <div class="media-body">
                        <h4 class="media-heading">{{ post.title }} <span
                                style="float: right;color: #9d9d9d;font-size:13px;">{{ post.upload_time|date:'Y-m-d H:i:s' }}</span>
                        </h4>
                        {{ post.article }}
                    </div>
                </a>
        <HR style="border:1px dashed #987cb9" width="100%" color=#987cb9 SIZE=1>
        </div>
    {% endfor %}
    <nav aria-label="Page navigation">
    <ul class="pagination">
        <li {% if not page.has_previous %}class="disabled"{% endif %}>
        <a {% if page.has_previous %}href="{% url 'App:index' %}?page={{ page.previous_page_number }}"{% endif %} aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
        </a>
        </li>
        {% for i in page.paginator.page_range %}
            <li {% if page.number == i %}class="active"{% endif %}><a href="{% url 'App:index' %}?page={{ i }}">{{ i }}</a></li>
        {% endfor %}
        <li {% if not page.has_next %}class="disabled"{% endif %}>
            <a {% if page.has_next %}href="{% url 'App:index' %}?page={{ page.next_page_number }}"{% endif %} aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
    </nav>
    {% endif %}
{% endblock %}

templates/home/send_posts.html
{% extends 'common/base.html' %}

{% block title %}
发表博客
{% endblock %}

{% block pagecontent %}
    <div class="page-header"><h2>发表博客</h2></div>
<form method="post" action="{% url 'App:send_posts' %}">
    {% csrf_token %}
    <label for="male">标题</label>
    <input type="text" placeholder="标题必须在1-20字以内" name="title" id="male" class="form-control" required />
    <br/>
    <label for="female">正文</label>
    <textarea name="article" id="female" class="form-control" style="height: 500px" required></textarea>
    <br>
{#    <div class="btn-group" role="group" aria-label="...">#}
        <button type="submit" class="btn btn-warning">发表</button>
    {#            <button type="button" class="btn btn-default">Right</button>#}
{#    </div>#}
</form>
{% endblock %}

templates/home/update_password.html
{% extends 'common/base.html' %}

{% block title %}
修改密码
{% endblock %}

{% block pagecontent %}
    <div class="page-header"><h2>修改密码</h2></div>
    <div class="col-md-4">
        <form action="{% url 'App:update_password' %}" method="post">
            {% csrf_token %}
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">旧密码</span>
                <input type="password" class="form-control" placeholder="请输入旧密码" aria-describedby="basic-addon1" name="password" required>
            </div>
            <br>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">新密码</span>
                <input type="password" class="form-control" placeholder="新密码在12个字符以内" aria-describedby="basic-addon1" name="new_password" required>
            </div>
            <br>
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">确认密码</span>
                <input type="password" class="form-control" placeholder="再次输入新密码" aria-describedby="basic-addon1" name="confirm" required>
            </div>
            <br>
            <div class="btn-group" role="group" aria-label="...">
                <button type="submit" class="btn btn-info">提交</button>
                <button type="reset" class="btn btn-default">重置</button>
            </div>
        </form>
    </div>
    <div class="col-md-8"></div>
{% endblock %}

templates/home/update_posts.html
{% extends 'common/base.html' %}

{% block title %}
修改博客
{% endblock %}

{% block pagecontent %}
    <div class="page-header"><h2>修改博客</h2></div>
<form method="post" action="{% url 'App:update_posts' %}?id={{ posts.id }}">
    {% csrf_token %}
    <label for="male">标题</label>
    <input type="text" value={{ posts.title }} placeholder="标题必须在1-20字以内" name="title" id="male" class="form-control" required />
    <br/>
    <label for="female">正文</label>
    <textarea name="article" id="female" class="form-control" style="height: 500px" required>{{ posts.article }}</textarea>
    <br>
{#    <div class="btn-group" role="group" aria-label="...">#}
        <button type="submit" class="btn btn-warning">提交</button>
{#        <button type="reset" class="btn btn-default">清空</button>#}
{#    </div>#}
</form>
{% endblock %}

templates/home/update_username.html
{% extends 'common/base.html' %}

{% block title %}
修改用户名
{% endblock %}

{% block pagecontent %}
    <div class="page-header"><h2>修改用户名</h2></div>
    <div class="col-md-4">
        <form action="{% url 'App:update_username' %}" method="post">
            {% csrf_token %}
            <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">用户名</span>
                <input type="text" class="form-control" value={{ request.user.username }} aria-describedby="basic-addon1" name="username" required>
            </div>
            <br>
            <div class="btn-group" role="group" aria-label="...">
                <button type="submit" class="btn btn-info">提交</button>
                <button type="button" class="btn btn-default">重置</button>
            </div>
        </form>
    </div>
    <div class="col-md-8"></div>
{% endblock %}

templates/home/upload.html
{% extends 'common/base.html' %}
{% load static from staticfiles %}

{% block title %}
上传头像
{% endblock %}

{% block pagecontent %}
    <div class="page-header"><h2>上传头像</h2></div>
    <form action="{% url 'App:upload' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div>
            <span><h3>当前头像：</h3></span>
            <img src="{% static user.icon %}">
        </div>
        <br>
        <br>
        <div class="input-group">
            <span><h3>选择头像：</h3></span>
            <input type="file" name="icon">
        </div>
        <br>
        <br>
        <div class="btn-group" role="group" aria-label="...">
            <button type="submit" class="btn btn-info">上传</button>
            <button type="reset" class="btn btn-default">重选</button>
        </div>
    </form>
{% endblock %}

templates/home/userActivate.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h2>欢迎：{{ username }}</h2>
    <h3>请点击右侧激活链接 进行账户的最后一步操作 <a href="{{ href }}">激活</a></h3>
</body>
</html>